#!/usr/bin/perl

#
# Copyright (C) 2017 Nethesis S.r.l.
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

# gitea certificate paths
my @certificates = (qw(
    /etc/pki/gitea/private/gitea.key
    /etc/pki/gitea/certs/gitea.crt
));

#
# nethserver-gitea-update event
#

my $event = 'nethserver-gitea-update';

event_actions($event, qw(
    initialize-default-databases 00
    nethserver-gitea-conf       30
));

event_templates($event, qw(
    /etc/gitea/app.ini
    /etc/httpd/conf.d/zz_gitea.conf
    /etc/httpd/conf.d/default-virtualhost.inc
));

event_services($event, 
   'gitea' => 'restart',
   'httpd-admin' => 'reload'
);


