#!/usr/bin/perl

#
# Copyright (C) 2017 Nethesis S.r.l.
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

# gitea certificate paths
my @certificates = (qw(
    /etc/pki/gitea/certs/gitea.crt
    /etc/pki/gitea/private/gitea.key
));

# 
# nethserver-gitea-update event
#
event_actions('nethserver-gitea-update', qw(
    initialize-default-databases 00
    nethserver-gitea-conf        30
));

event_templates('nethserver-gitea-update', 
    @certificates, qw(
    /etc/gitea/app.ini
    /etc/httpd/conf.d/zz_gitea.conf
    /etc/httpd/conf.d/default-virtualhost.inc
    /etc/sysconfig/gitea
));

event_services('nethserver-gitea-update', qw( 
    gitea restart
    httpd reload
));

#
# certificate-update event
#
event_templates('certificate-update', 
    @certificates
);

event_services('certificate-update', qw(
    gitea restart
));

#
# trusted-networks-modify event
#
event_templates('trusted-networks-modify', qw(
    /etc/httpd/conf.d/zz_gitea.conf
));

event_services('trusted-networks-modify', qw( 
    httpd reload
));

#
# nethserver-openssh-save event
#
event_templates('nethserver-openssh-save', qw(
    /etc/gitea/app.ini
));
event_services('nethserver-openssh-save', qw( 
    gitea restart
));


#
# TODO tls-policy-save event
#
#event_templates('tls-policy-save', qw(
#));
#event_actions('tls-policy-save', qw(
#));
#event_services('tls-policy-save', qw(
#));

#
# Backup Data
#
#event_templates(pre-backup-data'', qw(
#));
#event_actions('pre-backup-data'', qw(
#));
#event_services('pre-backup-data'', qw(
#));

#
# Restore Data
#
#event_templates('post-restore-data', qw(
#));
#event_actions('post-restore-data', qw(
#));
event_services('post-restore-data', qw(
    gitea restart
));

