#!/bin/bash

#check if database exists
dbtest=0
mysqlshow "gitea" > /dev/null 2>&1 && dbtest=1

if [ $dbtest -eq 1 ]; then
   # database exists
    exit 0
fi

# create new data base
password=`perl -e "use NethServer::Password; print NethServer::Password::store('gitea');"`

/usr/bin/mysql --defaults-file=/root/.my.cnf -e \
"CREATE DATABASE IF NOT EXISTS gitea;"
/usr/bin/mysql --defaults-file=/root/.my.cnf -e \
"CREATE USER gitea@localhost IDENTIFIED BY '$password';" 
/usr/bin/mysql --defaults-file=/root/.my.cnf -e \
"GRANT ALL PRIVILEGES ON gitea .* TO gitea@localhost;"

# write tables to it
mysql --defaults-file=/root/.my.cnf gitea < /usr/share/gitea/gitea-mysql-sample.sql

# Add PAM login source
epoch=$(date +%s)
/usr/bin/mysql --defaults-file=/root/.my.cnf -e \
"INSERT INTO gitea . login_source (id, type, name, is_actived, is_sync_enabled, cfg, created_unix, updated_unix) 
VALUES ('1', '4', 'Nethserver', '1', '0', '{\"ServiceName\":\"password-auth\"}', '$epoch', '$epoch');"

# temp app.ini with mysql credentials 
cat > /tmp/app.ini << EOF
APP_NAME = Gitea: Git with a cup of tea
RUN_USER = gitea
RUN_MODE = prod

[database]
DB_TYPE             = mysql
HOST                = 127.0.0.1:3306
NAME                = gitea
USER                = gitea
PASSWD              = $password
SSL_MODE            = disable

[log]
ROOT_PATH  = /var/lib/gitea/log
MODE       = console
BUFFER_LEN = 10000
LEVEL      = Trace
EOF

chown gitea:gitea /tmp/app.ini

# add local admin
pushd /var/lib/nethserver/gitea
su gitea -c "GITEA_WORK_DIR='/var/lib/nethserver/gitea' /usr/bin/gitea admin create-user --name gitea --password 'gitea' --email gitea@example.com --admin --config /tmp/app.ini"
popd

rm -rf /tmp/app.ini 