#!/bin/bash

# check home directory of gitea
curhomedir=$(eval echo "~gitea")

if [[ ! $curhomedir = "/var/lib/nethserver/gitea" ]]; then
   systemctl is-active --quiet gitea.service > /dev/null
   if [ $? -ne 0 ]; then
      # it is save to change gitea's home directory
      usermod -d /var/lib/nethserver/gitea gitea > /dev/null 2>&1
   else
     # this is strange: this seems to be on a fresh install and gitea is running ??
     # sorry we need to stop gitea to change it's home directory;
     # we trust the nethserver-gitea-update event to start gitea agian
     systemctl stop gitea.service
     usermod -d /var/lib/nethserver/gitea gitea > /dev/null 2>&1
   fi
fi

#check if database exists
dbtest=0
mysqlshow "gitea" > /dev/null 2>&1 && dbtest=1

if [ $dbtest -eq 1 ]; then
   # database exists nothing to do
    exit 0
fi

systemctl is-active --quiet gitea.service > /dev/null
if [ $? -eq 0 ]; then
     # this is strange: this seems to be on a fresh install and gitea is running ??
     # sorry we need to stop gitea;
     # we trust the nethserver-gitea-update event to start gitea agian
     systemctl stop gitea.service
fi

# create new database
password=`perl -e "use NethServer::Password; print NethServer::Password::store('gitea');"`

/usr/bin/mysql --defaults-file=/root/.my.cnf -e \
"CREATE DATABASE IF NOT EXISTS gitea;"
/usr/bin/mysql --defaults-file=/root/.my.cnf -e \
"CREATE USER gitea@localhost IDENTIFIED BY '$password';"
/usr/bin/mysql --defaults-file=/root/.my.cnf -e \
"GRANT ALL PRIVILEGES ON gitea .* TO gitea@localhost;"

# FIXME is 20s a save optimum ?
# populate database with tables on the fly by running gitea for 20s
# and add a local admin user
expand-template /etc/gitea/app.ini

pushd /var/lib/nethserver/gitea
timeout 20s su gitea -c \
"GITEA_WORK_DIR='/var/lib/nethserver/gitea' /usr/bin/gitea web --config /etc/gitea/app.ini"
su gitea -c \
"GITEA_WORK_DIR='/var/lib/nethserver/gitea' /usr/bin/gitea admin create-user --name gitea --password 'gitea' --email gitea@example.com --admin --config /etc/gitea/app.ini"
popd

# add PAM login source
epoch=$(date +%s)
/usr/bin/mysql --defaults-file=/root/.my.cnf -e \
"INSERT INTO gitea . login_source (id, type, name, is_actived, is_sync_enabled, cfg, created_unix, updated_unix) 
VALUES ('1', '4', 'Nethserver', '1', '0', '{\"ServiceName\":\"password-auth\"}', '$epoch', '$epoch');"
